### ISSUE TITLE
augment data must applied to only trainset

### ISSUE THREAD

**Issue by hansroh** [mkosaka1/Speech_Emotion_Recognition#1]
You should split train/valid set first.

And augment train set only.

Do not mess with augment data of trains set and valid set.

**Comment by hansroh** [comment]
Anyway your idea and transfer learning is very helpful.

Thanks.

**Comment by mkosaka1** [comment]
You are completely right, I will correct this and update my github. Thank
you for pointing that out!

Best,
Muriel Kosaka

**Comment by hansroh** [comment]
Also actors must be completely seperated train/valid set and with considering genders.

For example, testset contains actor 3, 6, 9, 12,... and trianset contains the others. Otherwise model will be overfit by actors.

**Comment by mkosaka1** [comment]
Very true. I will make the necessary changes and see how that affects my CNN model. Thank you again!
