### ISSUE TITLE
About transfer learning

### ISSUE THREAD

**Issue by iamyoungjin** [mkosaka1/Speech_Emotion_Recognition#2]
Hi , iam very appreicate because it is very useful to study to me.

I have a question about your project. 

Q)
when you use the transfer learning , where how can i access this data ?? 
I thought that is image data but i dont have wav image file ...

(you use the colab drive in 3.Transfer_Learning_Initial_Model but I dont know how can i attach that)

'''
from google.colab import drive
drive.mount('/content/drive')

import glob
angry = glob.glob('/content/drive/My Drive/train_logmel/angry/*.*')
calm = glob.glob('/content/drive/My Drive/train_logmel/calm/*.*')
disgust = glob.glob('/content/drive/My Drive/train_logmel/disgust/*.*')
fearful = glob.glob('/content/drive/My Drive/train_logmel/fearful/*.*')
happy = glob.glob('/content/drive/My Drive/train_logmel/happy/*.*')
neutral = glob.glob('/content/drive/My Drive/train_logmel/neutral/*.*')
sad = glob.glob('/content/drive/My Drive/train_logmel/sad/*.*')
surprised = glob.glob('/content/drive/My Drive/train_logmel/surprised/*.*')
'''
this section

can you help me about this ?

**Comment by iamyoungjin** [comment]
I solved it :-)

**Comment by Sowjanya109** [comment]
> I solved it :-)

Can you help me with how did you solve it?

**Comment by yihaoyao402** [comment]
> I solved it :-)

sorry to bother you， how do you fix it？
